name: CI -> Deploy to My website
on:
  push:
    branches: [ main ,dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftp.thewall.host4india.in
          user: gitaction@thewall.host4india.in
          password: t#y}ChwC47i(
         